<a href="https://colab.research.google.com/github/Shakhthi/Deep-Learning/blob/Excercise/Excercise/00_TensorFlow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Intro to Tensors**

In [1]:
# Import TensorFlow 
import tensorflow as tf 

In [2]:
# Version Checkup
tf.__version__

'2.9.2'

### **tf.constant()**

Creates a constant tensor.

The resulting tensor is populated with values of type dtype, as specified by arguments value and (optionally) shape (see examples below).

The argument value can be a constant value, or a list of values of type dtype. If value is a list, then the length of the list must be less than or equal to the number of elements implied by the shape argument (if specified). In the case where the list length is less than the number of elements specified by shape, the last element in the list will be used to fill the remaining entries.

The argument shape is optional. If present, it specifies the dimensions of the resulting tensor. If not present, the shape of value is used.

If the argument dtype is not specified, then the type is inferred from the type of value.

**Args**:

value: A constant value (or list) of output type dtype.

dtype: The type of the elements of the resulting tensor.

shape: Optional dimensions of resulting tensor.

name: Optional name for the tensor.

verify_shape: Boolean that enables verification of a shape of values.

**Returns:**
A Constant Tensor.

**Raises:**
TypeError: if shape is incorrectly specified or unsupported.

In [3]:
# Create a Tensor with tf.constent()
scalar = tf.constant(4)
print(scalar)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
# Check the number of dimensions
scalar.ndim

0

In [5]:
 # Create a vector with tf.constant()
vector = tf.constant([10,10])
print(vector) 

tf.Tensor([10 10], shape=(2,), dtype=int32)


In [6]:
vector.ndim 

1

In [7]:
# Create a matrix
matrix = tf.constant([[10,7],
                      [7,10]])
print(matrix)

tf.Tensor(
[[10  7]
 [ 7 10]], shape=(2, 2), dtype=int32)


In [8]:
float_matrix = tf.constant([[10., 7.],
                           [3.,2.],
                           [8.,9.]], dtype=tf.float16)  # Specify the data type with dtype
print(float_matrix)                           

tf.Tensor(
[[10.  7.]
 [ 3.  2.]
 [ 8.  9.]], shape=(3, 2), dtype=float16)


In [9]:
float_matrix.ndim

2

In [10]:
 #  Let's create a Tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
print(tensor)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)


In [11]:
tensor.ndim

3

  ### **tf.Variable()**

tf.Variable(  
    initial_value=None,
    trainable=None,
    validate_shape=True,
    caching_device=None,
    name=None,
    variable_def=None,
    dtype=None,
    import_scope=None,
    constraint=None,
    synchronization=tf.VariableSynchronization.AUTO,
    aggregation=tf.compat.v1.VariableAggregation.NONE,
    shape=None,
    experimental_enable_variable_lifting=True
  )

### **Creating Tensors with tf.Variable**

In [12]:
 # Create the same tensor with tf.variable
unchangable_tensor = tf.constant([10,7,4,5], shape=(2,2))
changable_tensor = tf.Variable([10,7,12,4])
unchangable_tensor, changable_tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 4,  5]], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([10,  7, 12,  4], dtype=int32)>)

### **Assinging values to the tensor**

In [13]:
# Changing Values
changable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([ 7,  7, 12,  4], dtype=int32)>

### **Creating random tensors**

**tf.random.normal**

 (
    shape,
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
 )

**Normal distribution**

Normal distribution, also known as the Gaussian distribution, is a probability distribution that is symmetric about the mean, showing that data near the mean are more frequent in occurrence than data far from the mean.

In graphical form, the normal distribution appears as a "bell curve".

In [14]:
random1 = tf.random.Generator.from_seed(42)
random1 = random1.normal(shape=(3,2))

random2 = tf.random.Generator.from_seed(42)
random2 = random2.normal(shape=(3,2))

random1, random2, random1 == random2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

**tf.random.uniform**

(
    shape,
    minval=0,
    maxval=None,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

**Uniform Distribution**

A uniform distribution, also called a rectangular distribution, is a probability distribution that has constant probability.


In [15]:
random3 = tf.random.Generator.from_seed(42)
random3 = random3.uniform(shape=(3,2))

random4 = tf.random.Generator.from_seed(42)
random4 = random4.uniform(shape=(3,2))

random3, random4, random3 == random4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.7493447 , 0.73561966],
        [0.45230794, 0.49039817],
        [0.1889317 , 0.52027524]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.7493447 , 0.73561966],
        [0.45230794, 0.49039817],
        [0.1889317 , 0.52027524]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffling the tensors

In [16]:
shuffle  = tf.constant([[1,2],
                       [9,8],
                       [5,0],
                       [4,3]]) 


In [17]:
tf.random.set_seed(7)   # Global level seed
tf.random.shuffle(shuffle)   # Operation level seed

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[5, 0],
       [1, 2],
       [4, 3],
       [9, 8]], dtype=int32)>

### Other ways to create tensors

In [18]:
tf.ones(10, tf.int32 )

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)>

In [19]:
tf.zeros(5)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>

**Creating tensors using numpy array's**

In [20]:
import numpy as np 

In [21]:
a = np.arange(1,25, dtype=np.int32)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [22]:
A = tf.constant(a, shape=(3,2,4), dtype=tf.int64)
print(A)

tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int64)


In [23]:
tf.Variable([1,2,3,4,5,6], dtype=tf.float32)
# In tf.Variable, can't alter the shape 

<tf.Variable 'Variable:0' shape=(6,) dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>

# Getting information from tensors
# (dtype, shape, Rank, size)

In [24]:
tensor  = tf.zeros(shape=[2,3,4,5])
print(tensor) 

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(2, 3, 4, 5), dtype=float32)


In [25]:
print(" Data type: ", tensor.dtype)
print(" Shape: ", tensor.shape)
print(" Rank: ", tensor.ndim)
print(" Size: ", tf.size(tensor)) 
print(" Size(Numpy): ", tf.size(tensor).numpy())

 Data type:  <dtype: 'float32'>
 Shape:  (2, 3, 4, 5)
 Rank:  4
 Size:  tf.Tensor(120, shape=(), dtype=int32)
 Size(Numpy):  120


# Indexing tensors

Tensors can be indexed like python lists

In [32]:
# Indexing
print(tensor[0][2][3][2])

tf.Tensor(0.0, shape=(), dtype=float32)


In [34]:
# Get first 2 elements of each dimension
print(tensor[:2, :1, :2, :2])

tf.Tensor(
[[[[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]]], shape=(2, 1, 2, 2), dtype=float32)


In [36]:
# Get the first element from each dimension from each index except for the final one
print(tensor[:1, :1, :1])

tf.Tensor([[[[0. 0. 0. 0. 0.]]]], shape=(1, 1, 1, 5), dtype=float32)


In [40]:
# create a rank 2 tensor
ten2 = tf.Variable([[1,2],
                   [3,4]], dtype=tf.int32)
print(ten2)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>


In [44]:
#Get last item
print(ten2[:,-1])

tf.Tensor([2 4], shape=(2,), dtype=int32)


# Expanding dimensions in a tensor


**tf.newaxis**

In [53]:
# Add in an extra dimension to our rank to dimension
ten3 = ten2[..., tf.newaxis]
print(ten3)

tf.Tensor(
[[[1]
  [2]]

 [[3]
  [4]]], shape=(2, 2, 1), dtype=int32)


**tf.expand_dims()**

tf.expand_dims(
    input, axis, name=None
)

In [54]:
#tf.expand_dims(ten3, axis=-1)  # Adding an axis at last

tf.expand_dims(ten3, axis=1)  # Adding an axis at index 0

<tf.Tensor: shape=(2, 1, 2, 1), dtype=int32, numpy=
array([[[[1],
         [2]]],


       [[[3],
         [4]]]], dtype=int32)>

In [56]:
tf.squeeze(ten3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

# Manipulating tensors (tensor operations)

**Basic Operations**

--- Addition

--- Subtraction 

--- Multiplication

--- Division







In [65]:
# Addition
ten_add = tf.Variable([[10,7],
                      [4,3]])
print(ten_add + 10)
print()
print(ten_add) # Original tensor is unchanged

tf.Tensor(
[[20 17]
 [14 13]], shape=(2, 2), dtype=int32)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10,  7],
       [ 4,  3]], dtype=int32)>


In [67]:
# Subtraction
ten_sub = tf.Variable([[10,7],
                      [4,3]])
print(ten_sub - 10)
print()
print(ten_sub) # Original tensor is unchanged

tf.Tensor(
[[ 0 -3]
 [-6 -7]], shape=(2, 2), dtype=int32)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10,  7],
       [ 4,  3]], dtype=int32)>


In [71]:
# Multiplication
ten_m  = tf.Variable([[10,7],
                      [4,3]])
print(ten_m*3)

print()

print(tf.math.multiply(ten_m, 12))

tf.Tensor(
[[30 21]
 [12  9]], shape=(2, 2), dtype=int32)

tf.Tensor(
[[120  84]
 [ 48  36]], shape=(2, 2), dtype=int32)


In [68]:
# Division
ten_div = tf.Variable([[10,7],
                      [4,3]])
ten_div/2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [2. , 1.5]])>