<a href="https://colab.research.google.com/github/Shakhthi/Deep-Learning/blob/Excercise/Excercise/00_TensorFlow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Intro to Tensors**

In [1]:
# Import TensorFlow 
import tensorflow as tf 

In [2]:
# Version Checkup
tf.__version__

'2.9.2'

### **tf.constant()**

Creates a constant tensor.

The resulting tensor is populated with values of type dtype, as specified by arguments value and (optionally) shape (see examples below).

The argument value can be a constant value, or a list of values of type dtype. If value is a list, then the length of the list must be less than or equal to the number of elements implied by the shape argument (if specified). In the case where the list length is less than the number of elements specified by shape, the last element in the list will be used to fill the remaining entries.

The argument shape is optional. If present, it specifies the dimensions of the resulting tensor. If not present, the shape of value is used.

If the argument dtype is not specified, then the type is inferred from the type of value.

**Args**:

value: A constant value (or list) of output type dtype.

dtype: The type of the elements of the resulting tensor.

shape: Optional dimensions of resulting tensor.

name: Optional name for the tensor.

verify_shape: Boolean that enables verification of a shape of values.

**Returns:**
A Constant Tensor.

**Raises:**
TypeError: if shape is incorrectly specified or unsupported.

In [3]:
# Create a Tensor with tf.constent()
scalar = tf.constant(4)
print(scalar)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
# Check the number of dimensions
scalar.ndim

0

In [5]:
 # Create a vector with tf.constant()
vector = tf.constant([10,10])
print(vector) 

tf.Tensor([10 10], shape=(2,), dtype=int32)


In [6]:
vector.ndim 

1

In [7]:
# Create a matrix
matrix = tf.constant([[10,7],
                      [7,10]])
print(matrix)

tf.Tensor(
[[10  7]
 [ 7 10]], shape=(2, 2), dtype=int32)


In [8]:
float_matrix = tf.constant([[10., 7.],
                           [3.,2.],
                           [8.,9.]], dtype=tf.float16)  # Specify the data type with dtype
print(float_matrix)                           

tf.Tensor(
[[10.  7.]
 [ 3.  2.]
 [ 8.  9.]], shape=(3, 2), dtype=float16)


In [9]:
float_matrix.ndim

2

In [10]:
 #  Let's create a Tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
print(tensor)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)


In [11]:
tensor.ndim

3

  ### **tf.Variable()**

tf.Variable(  
    initial_value=None,
    trainable=None,
    validate_shape=True,
    caching_device=None,
    name=None,
    variable_def=None,
    dtype=None,
    import_scope=None,
    constraint=None,
    synchronization=tf.VariableSynchronization.AUTO,
    aggregation=tf.compat.v1.VariableAggregation.NONE,
    shape=None,
    experimental_enable_variable_lifting=True
  )

### **Creating Tensors with tf.Variable**

In [12]:
 # Create the same tensor with tf.variable
unchangable_tensor = tf.constant([10,7,4,5], shape=(2,2))
changable_tensor = tf.Variable([10,7,12,4])
unchangable_tensor, changable_tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 4,  5]], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([10,  7, 12,  4], dtype=int32)>)

### **Assinging values to the tensor**

In [13]:
# Changing Values
changable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([ 7,  7, 12,  4], dtype=int32)>

### **Creating random tensors**

**tf.random.normal**

 (
    shape,
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
 )

**Normal distribution**

Normal distribution, also known as the Gaussian distribution, is a probability distribution that is symmetric about the mean, showing that data near the mean are more frequent in occurrence than data far from the mean.

In graphical form, the normal distribution appears as a "bell curve".

In [14]:
random1 = tf.random.Generator.from_seed(42)
random1 = random1.normal(shape=(3,2))

random2 = tf.random.Generator.from_seed(42)
random2 = random2.normal(shape=(3,2))

random1, random2, random1 == random2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

**tf.random.uniform**

(
    shape,
    minval=0,
    maxval=None,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

**Uniform Distribution**

A uniform distribution, also called a rectangular distribution, is a probability distribution that has constant probability.


In [15]:
random3 = tf.random.Generator.from_seed(42)
random3 = random3.uniform(shape=(3,2))

random4 = tf.random.Generator.from_seed(42)
random4 = random4.uniform(shape=(3,2))

random3, random4, random3 == random4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.7493447 , 0.73561966],
        [0.45230794, 0.49039817],
        [0.1889317 , 0.52027524]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.7493447 , 0.73561966],
        [0.45230794, 0.49039817],
        [0.1889317 , 0.52027524]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffling the tensors

In [16]:
shuffle  = tf.constant([[1,2],
                       [9,8],
                       [5,0],
                       [4,3]]) 


In [17]:
tf.random.set_seed(7)   # Global level seed
tf.random.shuffle(shuffle)   # Operation level seed

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[5, 0],
       [1, 2],
       [4, 3],
       [9, 8]], dtype=int32)>

### Other ways to create tensors

In [18]:
tf.ones(10, tf.int32 )

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)>

In [19]:
tf.zeros(5)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>

**Creating tensors using numpy array's**

In [20]:
import numpy as np 

In [21]:
a = np.arange(1,25, dtype=np.int32)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [22]:
A = tf.constant(a, shape=(3,2,4), dtype=tf.int64)
print(A)

tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int64)


In [23]:
tf.Variable([1,2,3,4,5,6], dtype=tf.float32)
# In tf.Variable, can't alter the shape 

<tf.Variable 'Variable:0' shape=(6,) dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>

# Getting information from tensors
# (dtype, shape, Rank, size)

In [24]:
tensor  = tf.zeros(shape=[2,3,4,5])
print(tensor) 

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(2, 3, 4, 5), dtype=float32)


In [25]:
print(" Data type: ", tensor.dtype)
print(" Shape: ", tensor.shape)
print(" Rank: ", tensor.ndim)
print(" Size: ", tf.size(tensor)) 
print(" Size(Numpy): ", tf.size(tensor).numpy())

 Data type:  <dtype: 'float32'>
 Shape:  (2, 3, 4, 5)
 Rank:  4
 Size:  tf.Tensor(120, shape=(), dtype=int32)
 Size(Numpy):  120


# Indexing tensors

Tensors can be indexed like python lists

In [26]:
# Indexing
print(tensor[0][2][3][2])

tf.Tensor(0.0, shape=(), dtype=float32)


In [27]:
# Get first 2 elements of each dimension
print(tensor[:2, :1, :2, :2])

tf.Tensor(
[[[[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]]], shape=(2, 1, 2, 2), dtype=float32)


In [28]:
# Get the first element from each dimension from each index except for the final one
print(tensor[:1, :1, :1])

tf.Tensor([[[[0. 0. 0. 0. 0.]]]], shape=(1, 1, 1, 5), dtype=float32)


In [29]:
# create a rank 2 tensor
ten2 = tf.Variable([[1,2],
                   [3,4]], dtype=tf.int32)
print(ten2)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>


In [30]:
#Get last item
print(ten2[:,-1])

tf.Tensor([2 4], shape=(2,), dtype=int32)


# Expanding dimensions in a tensor


**tf.newaxis**

In [31]:
# Add in an extra dimension to our rank to dimension
ten3 = ten2[..., tf.newaxis]
print(ten3)

tf.Tensor(
[[[1]
  [2]]

 [[3]
  [4]]], shape=(2, 2, 1), dtype=int32)


**tf.expand_dims()**

tf.expand_dims(
    input, axis, name=None
)

In [32]:
#tf.expand_dims(ten3, axis=-1)  # Adding an axis at last

tf.expand_dims(ten3, axis=1)  # Adding an axis at index 0

<tf.Tensor: shape=(2, 1, 2, 1), dtype=int32, numpy=
array([[[[1],
         [2]]],


       [[[3],
         [4]]]], dtype=int32)>

In [33]:
tf.squeeze(ten3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

# Manipulating tensors (tensor operations)

**Basic Operations**

--- Addition

--- Subtraction 

--- Multiplication

--- Division







In [34]:
# Addition
ten_add = tf.Variable([[10,7],
                      [4,3]])
print(ten_add + 10)
print()
print(ten_add) # Original tensor is unchanged

print(tf.math.add(ten_add, 10))

tf.Tensor(
[[20 17]
 [14 13]], shape=(2, 2), dtype=int32)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10,  7],
       [ 4,  3]], dtype=int32)>
tf.Tensor(
[[20 17]
 [14 13]], shape=(2, 2), dtype=int32)


In [35]:
# Subtraction
ten_sub = tf.Variable([[10,7],
                      [4,3]])
print(ten_sub - 10)
print()
print(ten_sub) # Original tensor is unchanged
print(tf.math.subtract(ten_sub, 2))

tf.Tensor(
[[ 0 -3]
 [-6 -7]], shape=(2, 2), dtype=int32)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10,  7],
       [ 4,  3]], dtype=int32)>
tf.Tensor(
[[8 5]
 [2 1]], shape=(2, 2), dtype=int32)


In [36]:
# Multiplication
ten_m  = tf.Variable([[10,7],
                      [4,3]])
print(ten_m*3)
print()
print(tf.math.multiply(ten_m, 12))

tf.Tensor(
[[30 21]
 [12  9]], shape=(2, 2), dtype=int32)

tf.Tensor(
[[120  84]
 [ 48  36]], shape=(2, 2), dtype=int32)


In [37]:
# Division
ten_div = tf.Variable([[10,7],
                      [4,3]])
print(ten_div/2)
print(tf.math.divide(ten_div, 3))

tf.Tensor(
[[5.  3.5]
 [2.  1.5]], shape=(2, 2), dtype=float64)
tf.Tensor(
[[3.33333333 2.33333333]
 [1.33333333 1.        ]], shape=(2, 2), dtype=float64)


## Matrix Multiplication


--- tf.linalg.matmul()

--- U @ V 

--- U * V (Element-wise multiplication)

--- tf.tensordot()









In [38]:
# Matrix Multiplication in tensorflow
X = tf.constant([[1,2,6],
                 [10,1,7],
                 [2,3,4]])
Y = tf.constant([[2,5],
                 [6,7],
                 [1,8]])
print(tf.linalg.matmul(a=X, b=Y))

tf.Tensor(
[[ 20  67]
 [ 33 113]
 [ 26  63]], shape=(3, 2), dtype=int32)


In [39]:
# Matrix multiplication in python with @
print(X @ Y)

tf.Tensor(
[[ 20  67]
 [ 33 113]
 [ 26  63]], shape=(3, 2), dtype=int32)


In [40]:
# Element wise multiplication
# print(X * Y)

In [41]:
# Matrix Multiplication with same shape
U = tf.constant([[1,2],
                  [3,4],
                  [5,6]])
V = tf.constant([[7,8],
                 [9,10],
                 [11,12]])


In [42]:
print(tf.linalg.matmul(U,V))

InvalidArgumentError: ignored

**tf.reshape(
      tensor, shape, name=None
  )**  

tf.reshape() flattens the tensor object and then rearranges according to the shape passed.

In [43]:
# Analysing the above issue
print(" Matrix Multiplication using tf.reshape()")
print(tf.linalg.matmul(tf.reshape(U, (2,3)),V))
print()
print(" Reshaped tensor U ")
print(tf.reshape(U, (2,3)))

 Matrix Multiplication using tf.reshape()
tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)

 Reshaped tensor U 
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


**tf.transpose(
    a, perm=None, conjugate=False, name='transpose'
)**

tf.transpose() simply interchanges the dimensions 

In [44]:
print(" Matrix multiplication using tf.transpose() ")
print(tf.linalg.matmul(tf.transpose(U),V))
print()
print(" Transposed Matrix U")
print(tf.transpose(U))


 Matrix multiplication using tf.transpose() 
tf.Tensor(
[[ 89  98]
 [116 128]], shape=(2, 2), dtype=int32)

 Transposed Matrix U
tf.Tensor(
[[1 3 5]
 [2 4 6]], shape=(2, 3), dtype=int32)


## Changing the Data type of the tensor

## Finding max and min position elements

## Squeezing a tensor (Removing all 1-D series)

## One-hot Encoding

In [45]:
# create a list of indices
List = [1,2,3,4]
List

[1, 2, 3, 4]

In [46]:
# one hot Encoding
tf.one_hot(List, depth= tf.size(List), on_value=4, off_value=-1, dtype=tf.int32)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[-1,  4, -1, -1],
       [-1, -1,  4, -1],
       [-1, -1, -1,  4],
       [-1, -1, -1, -1]], dtype=int32)>

## Some Math operations

In [47]:
H = tf.range(1,10)

In [48]:
# Squaring a tensor
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [49]:
# Taking square root to a tensor
tf.math.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [50]:
# Taking log transformation
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# Tensors & Numpy

Tensors beautifully interacts with Numpy arrays

In [51]:
I = tf.constant(np.array([1., 3., 4., 7. ]))

In [52]:
# Converting tensor to a numpy array
np.array(I)
print(type(np.array(I)))

<class 'numpy.ndarray'>


In [53]:
# Converting Numpy array to a tensor
tf.constant(np.array(I))

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([1., 3., 4., 7.])>

# Finding Access to GPU

In [54]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]